Add export ignored files to .gitattributes
Move THIRDPARTY_NOTICE files to addons/godot_xterm so they will be
included with asset-lib downloads.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -239,3 +239,38 @@ jobs:
         with:
           run: ./godot_executable/${{ env.GODOT }} --no-window -s addons/gut/gut_cmdln.gd -gconfig=test/.gutconfig.unix.json
 
+
+  # Git archive should only include addons/godot_xterm directory.
+  check-archive:
+    name: 'Check Archive'
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: recursive
+    - name: Create git archive
+      run: git archive -o archive.zip HEAD
+    - name: Extract archive
+      run: mkdir -p /tmp/unzipped && unzip archive.zip -d /tmp/unzipped
+    - name: Check that archive only contains addons directory
+      run: |
+        shopt -s nullglob dotglob
+        ls -lR /tmp/unzipped
+        files=(/tmp/unzipped/*)
+        if [ ${#files[@]} -ne 1 ]; then
+          echo "Wrong number of files in archive (${#files[@]}) expected 1."
+          exit 1
+        fi
+        if [ ! -d "/tmp/unzipped/addons" ]; then
+          echo "Expected directory (addons) not found."
+          exit 1
+        fi
+        files=(/tmp/unzipped/addons)
+        if [ ${#files[@]} -ne 1 ]; then
+          echo "Wrong number of files in addons directory (${#files[@]}) expected 1."
+          exit 1
+        fi
+        if [ ! -d "/tmp/unzipped/addons/godot_xterm" ]; then
+          echo "Expected directory (addons/godot_xterm) not found."
+          exit 1
+        fi
